### PR TITLE
updated dependencies to remove security vulnerabilities.

### PR DESCRIPTION
**Pull request by butson**
modified source to compile with incompatiabilities with updated dependencies.
1 medium security vulnerability in jackson-databind

### CODE REVIEW

**Comment by adriansuarez** [comment]
Does this duplicate PR #75 that @eresende-nuodb posted or make it obsolete?

**Comment by eresende-nuodb** [comment]
I have closed #75 since it is an uncompleted PR. We should keep this PR instead.
As for the implementation of dependabot, it makes sense for other repositories. This repository will be discontinued in the future as soon we have the new migrator tool.

**Comment by dbutson-mdsol** [comment]
@eresende-nuodb   @rshaull  still looking for approvals. @eresende-nuodb  do you just want to do the merge when it's approved.

**Review by eresende-nuodb — APPROVED** [review]

**Comment by eresende-nuodb** [comment]
@dbutson-mdsol I can do the merge as soon @rshaull approves.

**Review by bbp9857 — APPROVED** [review]

**Pull request merged**
